(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const P=(window.APP_PREFIX||'kenchan_'); const uiKey=P+'ui_v13', readKey=P+'reading_events_v2', monthKey=P+'monthly_records_v2', settingsKey=P+'settings_v2', candKey=P+'candidates_v2', coverKey=P+'covers_v1';
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let ui=load(uiKey,{theme:'pink',days:[1,2,3,4,5],excludeHolidays:true,growth:'ことば',recStatuses:{}});
const themes={red:['#d94b55','#fff0f1'],blue:['#4779c7','#eef5ff'],yellow:['#c99316','#fff8dc'],green:['#4f8b68','#edf8f1'],orange:['#e87936','#fff1e8'],pink:['#e85d75','#fff0f4'],black:['#303033','#f2f2f2']};
function theme(){let t=themes[ui.theme]||themes.pink;document.documentElement.style.setProperty('--accent',t[0]);document.documentElement.style.setProperty('--accent-soft',t[1])}theme();
// tactile state
addEventListener('pointerdown',e=>{let b=e.target.closest('button');if(b)b.classList.add('is-pressed')});addEventListener('pointerup',()=>$$('.is-pressed').forEach(x=>x.classList.remove('is-pressed')));addEventListener('pointercancel',()=>$$('.is-pressed').forEach(x=>x.classList.remove('is-pressed')));
const norm=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[\s　・･?？!！「」『』（）()―ー\-]/g,'');
function master(){let ov=load(P+'clean_overrides_v1',{}),ub=load(P+'user_books_v1',[]);return [...(window.MASTER_BOOKS||[]),...ub].map(b=>({...b,...(ov[b.id]||{})})).filter(b=>!b.deleted)}
function recBook(title,all=master()){let n=norm(title),id=(window.KAHO_LINKS||{})[n];return (id&&all.find(b=>b.id===id))||all.find(b=>norm(b.title)===n)}
function reads(){return load(readKey,[])} function count(rs=reads()){return rs.reduce((a,r)=>a+(+r.count||1),0)}
function settings(){return load(settingsKey,{birthday:'2025-04-05',goal:30000,monthGoal:500})}
function monthStr(d=new Date()){return d.toISOString().slice(0,7)}
function monthReads(m){return reads().filter(r=>(r.date||'').slice(0,7)===m)}
function isHoliday(d){let md=(d.getMonth()+1)+'-'+d.getDate();return ['1-1','2-11','2-23','4-29','5-3','5-4','5-5','8-11','11-3','11-23'].includes(md)}
function eligibleDays(m){let [y,mo]=m.split('-').map(Number),n=new Date(y,mo,0).getDate(),c=0;for(let i=1;i<=n;i++){let d=new Date(y,mo-1,i),wd=d.getDay();if(ui.days.includes(wd)&&!(ui.excludeHolidays&&isHoliday(d)))c++}return c||1}
function cover(book){let cv=load(coverKey,{});return (book?.isbn&&cv[book.isbn])||book?.cover||''}
function coverEl(book){let c=cover(book);return `<div class="v13-cover">${c?`<img src="${c}" alt="">`:'<span>📖</span>'}</div>`}
function injectQuick(){let main=$('main');if(!main||$('#v13Quick'))return;let box=document.createElement('div');box.id='v13Quick';main.insertBefore(box,main.firstChild);renderQuick()}
function renderQuick(){let b=$('#v13Quick');if(!b)return;let m=monthStr(),mc=count(monthReads(m)),tot=count(),avg=(mc/eligibleDays(m)).toFixed(1),goal=settings().monthGoal||500;b.innerHTML=`<div class="v13-q"><b>${tot}</b>累計</div><div class="v13-q"><b>${mc}</b>今月</div><div class="v13-q"><b>${avg}</b>1日平均</div><div class="v13-q"><b>${goal}</b>今月目標</div>`}
setTimeout(injectQuick,100);
// Settings: theme + weekdays
const sdlg=$('#settingsDlg'); if(sdlg){let h=sdlg.querySelector('.shop-head');let panel=document.createElement('section');panel.innerHTML=`<h3>見た目</h3><div class="theme-grid" id="themeGrid"></div><h3>読む曜日</h3><div class="v13-pills" id="dayPills"></div><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" id="v13Holiday"> 平日の祝日を除く</label><p class="v8meta">この設定で月別の1日平均と残り対象日数を計算します。</p>`;h.after(panel);let names=['日','月','火','水','木','金','土'],cols={red:'#d94b55',blue:'#4779c7',yellow:'#e5b92f',green:'#4f8b68',orange:'#e87936',pink:'#e85d75',black:'#303033'};$('#themeGrid').innerHTML=Object.entries(cols).map(([k,c])=>`<button type="button" class="theme-dot ${ui.theme===k?'on':''}" data-theme="${k}" style="background:${c}" aria-label="${k}"></button>`).join('');$('#dayPills').innerHTML=names.map((n,i)=>`<button type="button" class="v13-pill ${ui.days.includes(i)?'on':''}" data-day="${i}">${n}</button>`).join('');$('#v13Holiday').checked=ui.excludeHolidays;$('#themeGrid').onclick=e=>{let x=e.target.closest('[data-theme]');if(!x)return;ui.theme=x.dataset.theme;save(uiKey,ui);theme();$$('.theme-dot').forEach(z=>z.classList.toggle('on',z===x))};$('#dayPills').onclick=e=>{let x=e.target.closest('[data-day]');if(!x)return;let d=+x.dataset.day;ui.days=ui.days.includes(d)?ui.days.filter(v=>v!==d):[...ui.days,d].sort();if(!ui.days.length)ui.days=[1,2,3,4,5];save(uiKey,ui);x.classList.toggle('on',ui.days.includes(d));renderQuick()};$('#v13Holiday').onchange=e=>{ui.excludeHolidays=e.target.checked;save(uiKey,ui);renderQuick()}}
// reading visual shelf and +/- counts
function addReadingShelf(){let d=$('#readingDlg');if(!d||$('#v13ReadShelf'))return;let title=d.querySelector('h3');if(!title)return;let sec=document.createElement('section');sec.id='v13ReadShelf';sec.innerHTML='<h3>今日読む本</h3><div id="v13ReadBooks"></div>';title.before(sec);renderReadShelf()}
function renderReadShelf(){let box=$('#v13ReadBooks');if(!box)return;let recent=[...master()].slice(0,12);if(!recent.length){box.innerHTML='<div class="v13-empty">📚<b>まだ本がありません</b>スキャンして最初の1冊を登録しましょう</div>';return}box.innerHTML=recent.map(b=>`<div class="v13-bookrow">${coverEl(b)}<div class="grow"><strong>${b.title}</strong><small>${b.author||''}</small></div><button class="v13-readpick" data-title="${encodeURIComponent(b.title)}">＋1</button></div>`).join('');box.onclick=e=>{let x=e.target.closest('.v13-readpick');if(!x)return;$('#readTitle').value=decodeURIComponent(x.dataset.title);$('#readCount').value=1;$('#readTitle').scrollIntoView({behavior:'smooth',block:'center'})}}
$('#openReading')?.addEventListener('click',()=>setTimeout(addReadingShelf,50));
// Analytics bars by month
function enhanceAnalytics(){let body=$('#analyticsBody');if(!body)return;let old=$('#v13Analytics');old?.remove();let months=[...new Set(reads().map(r=>(r.date||'').slice(0,7)).filter(Boolean))].sort().slice(-12);let vals=months.map(m=>({m,total:count(monthReads(m)),avg:count(monthReads(m))/eligibleDays(m)})),mx=Math.max(1,...vals.map(v=>v.total));let div=document.createElement('div');div.id='v13Analytics';div.innerHTML=`<h3>月ごとの回数</h3><div class="v13-bars">${vals.map(v=>`<div class="v13-barline"><span>${v.m.slice(5)}月</span><div class="v13-track"><div class="v13-fill" style="width:${v.total/mx*100}%"></div></div><b>${v.total}</b></div>`).join('')}</div><h3>対象日1日平均</h3><div class="v13-bars">${vals.map(v=>`<div class="v13-barline"><span>${v.m.slice(5)}月</span><div class="v13-track"><div class="v13-fill" style="width:${Math.min(100,v.avg/Math.max(1,...vals.map(x=>x.avg))*100)}%"></div></div><b>${v.avg.toFixed(1)}</b></div>`).join('')}</div>`;body.prepend(div)}
$('#openAnalytics')?.addEventListener('click',()=>setTimeout(enhanceAnalytics,80));
// Journal prompts + target
function enhanceMonth(){let st=$('#monthStats');if(!st||$('#v13Journal'))return;let m=$('#monthKey')?.value||monthStr(),rec=load(monthKey,{});let sec=document.createElement('div');sec.id='v13Journal';sec.className='v13-journal';sec.innerHTML=`<label>🎯 今月の目標回数<input id="v13MonthGoal" type="number" value="${rec[m]?.goal||settings().monthGoal||500}"></label><label>🌱 今月できるようになったこと<textarea id="v13Growth" placeholder="小さな変化でOK"></textarea></label><label>😊 よく笑った・反応した本<textarea id="v13Smile" placeholder="タイトルとひとこと"></textarea></label><label>🔁 何度も持ってきた本<textarea id="v13Again" placeholder="お気に入りの変化"></textarea></label><label>💌 未来に残したいひとこと<textarea id="v13Letter" placeholder="今月のあなたへ"></textarea></label>`;st.after(sec);let x=rec[m]?.v13||{};['Growth','Smile','Again','Letter'].forEach(k=>$('#v13'+k).value=x[k.toLowerCase()]||'');}
$('#openMonthly')?.addEventListener('click',()=>setTimeout(enhanceMonth,80));$('#monthKey')?.addEventListener('change',()=>{ $('#v13Journal')?.remove();enhanceMonth()});$('#saveMonth')?.addEventListener('click',()=>{let m=$('#monthKey')?.value||monthStr(),all=load(monthKey,{});all[m]=all[m]||{};all[m].goal=+($('#v13MonthGoal')?.value||0);all[m].v13={growth:$('#v13Growth')?.value||'',smile:$('#v13Smile')?.value||'',again:$('#v13Again')?.value||'',letter:$('#v13Letter')?.value||''};save(monthKey,all);renderQuick()});
// Recommendations dialog
let menu=$('#menu');if(menu&&!$('#openMonthlyRec')){let b=document.createElement('button');b.id='openMonthlyRec';b.textContent='✨ 今月のおすすめ';let ana=$('#openAnalytics');menu.insertBefore(b,ana);let d=document.createElement('dialog');d.id='monthlyRecDlg';d.className='v8dlg';d.innerHTML=`<div class="shop-head"><strong>今月のおすすめ 20冊</strong><button data-v13close>閉じる</button></div><div class="v13-pills" id="recFilters"><button class="v13-pill on" data-rf="all">すべて</button><button class="v13-pill" data-rf="owned">所有</button><button class="v13-pill" data-rf="buy">購入予定</button><button class="v13-pill" data-rf="borrow">図書館</button></div><div id="v13RecReason" class="v13-journal"></div><div id="v13RecList" class="v13-recgrid"></div><button id="batchReserve" class="shop-primary" style="margin-top:12px">📚 図書館候補をまとめて確認</button><div id="batchReserveList"></div>`;document.body.appendChild(d);d.querySelector('[data-v13close]').onclick=()=>d.close();b.onclick=()=>{menu.hidden=true;renderRecs();d.showModal()};$('#recFilters').onclick=e=>{let x=e.target.closest('[data-rf]');if(!x)return;$$('#recFilters .v13-pill').forEach(z=>z.classList.toggle('on',z===x));renderRecs(x.dataset.rf)};$('#batchReserve').onclick=renderReserveQueue;}
function recPool(){let R=window.RECOMMENDATIONS||{},levels=['5A','4A','3A','2A','A','B','C','D','E','F','G','H','I'],arr=[];levels.forEach(l=>(R.kumon?.[l]||[]).forEach(t=>arr.push({title:t,program:'KUMON '+l})));(R.sukusuku||[]).forEach(t=>arr.push({title:t,program:'すくすく館'}));(R.nakayoshi||[]).forEach(t=>arr.push({title:t,program:'なかよし館'}));let seen=new Set();return arr.filter(x=>!seen.has(norm(x.title))&&seen.add(norm(x.title)))}
function monthly20(){let pool=recPool(),owned=master(),m=new Date().getMonth()+1,season=m>=9&&m<=11?'秋':m===12?'冬・クリスマス':m<=2?'冬':m<=5?'春':'夏';let scored=pool.map(x=>{let b=recBook(x.title,owned);let s=x.program.includes('5A')?5:x.program.includes('4A')?4:2;if(b)s+=2;if((x.title||'').match(/秋|月|どんぐり|虫|おつき|ハロウィン/)&&season==='秋')s+=5;return {...x,...(b||{}),score:s,status:ui.recStatuses[norm(x.title)]||(b?'owned':'borrow')}}).sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title,'ja'));return pool.length?scored.slice(0,20):owned.slice(0,20).map(b=>({...b,status:'owned',program:'本棚'}))}
function renderRecs(filter='all'){let list=monthly20().filter(x=>filter==='all'||x.status===filter);let s=settings(),bd=s.birthday?new Date(s.birthday):null,age=bd?Math.max(0,Math.floor((Date.now()-bd)/(864e5*30.44))):null;$('#v13RecReason').innerHTML=`<b>今月のテーマ：${ui.growth} × ${new Date().getMonth()+1}月</b><br><small>${age!=null?age+'か月・':''}季節と推奨段階、本棚の状況から20冊を組み合わせています。</small>`;$('#v13RecList').innerHTML=list.map((b,i)=>`<div class="v13-rec">${coverEl(b)}<strong>${b.title}</strong><small class="meta" data-meta="${encodeURIComponent(b.title)}">${b.author||'著者を確認中'}${b.publisher?' · '+b.publisher:''}<br>${b.program||''}</small><select class="v13-status" data-status="${encodeURIComponent(b.title)}"><option value="owned" ${b.status==='owned'?'selected':''}>📚 所有</option><option value="buy" ${b.status==='buy'?'selected':''}>🛍 購入予定</option><option value="borrow" ${b.status==='borrow'?'selected':''}>🏛 図書館</option></select></div>`).join('')||'<div class="v13-empty">該当する本はありません</div>';$$('[data-status]').forEach(x=>x.onchange=()=>{ui.recStatuses[norm(decodeURIComponent(x.dataset.status))]=x.value;save(uiKey,ui)});enrichVisibleMeta()}
async function enrichVisibleMeta(){for(const el of $$('[data-meta]')){if(!el.textContent.includes('確認中'))continue;let title=decodeURIComponent(el.dataset.meta);try{let q=encodeURIComponent('intitle:'+title),r=await fetch('https://www.googleapis.com/books/v1/volumes?q='+q+'&maxResults=1&langRestrict=ja'),j=await r.json(),v=j.items?.[0]?.volumeInfo;if(v){el.innerHTML=`${(v.authors||[]).join('・')||'著者情報なし'}${v.publisher?' · '+v.publisher:''}<br>${el.innerHTML.split('<br>')[1]||''}`;let img=v.imageLinks?.thumbnail;if(img){let card=el.closest('.v13-rec'),im=card?.querySelector('.v13-cover');if(im&&img)im.innerHTML=`<img src="${img.replace('http:','https:')}" alt="">`}}}catch{}}}
function renderReserveQueue(){let books=monthly20().filter(x=>(ui.recStatuses[norm(x.title)]||x.status)==='borrow'),libs=settings().libs||[];$('#batchReserveList').innerHTML=books.length?`<div class="v13-journal"><b>${books.length}冊を予約候補にしました</b><p>図書館サイトでは利用者ログインが必要なため、予約確定は各館で行います。</p>${books.map(b=>`<div class="v13-bookrow"><div class="grow"><strong>${b.title}</strong><small>${b.author||''}</small></div><a target="_blank" rel="noopener" href="https://calil.jp/search?q=${encodeURIComponent(b.title)}">所蔵確認</a></div>`).join('')}</div>`:'<p>図書館候補はありません。</p>'}
// Candidate UI: multi KUMON check, search, sort, metadata enrichment
const cdlg=$('#candidateDlg');if(cdlg&&!$('#v13CandTools')){let top=cdlg.querySelector('.v8grid');let sec=document.createElement('div');sec.id='v13CandTools';sec.innerHTML=`<input id="v13CandSearch" placeholder="🔎 タイトル・著者・出版社で検索"><div class="v13-pills" id="v13Levels">${['5A','4A','3A','2A','A','B','C','D','E','F','G','H','I'].map(x=>`<button type="button" class="v13-pill on" data-lv="${x}">${x}</button>`).join('')}</div><select id="v13CandSort"><option value="title">あいうえお順</option><option value="author">作者順</option><option value="publisher">出版社順</option></select>`;top.after(sec);let refresh=()=>setTimeout(enhanceCandidateList,120);$('#v13CandSearch').oninput=refresh;$('#v13CandSort').onchange=refresh;$('#v13Levels').onclick=e=>{let x=e.target.closest('[data-lv]');if(x){x.classList.toggle('on');refresh()}}}
function enhanceCandidateList(){let box=$('#candidateList');if(!box)return;let q=norm($('#v13CandSearch')?.value),sort=$('#v13CandSort')?.value||'title',levels=$$('#v13Levels .on').map(x=>x.dataset.lv);let rows=[...box.children];rows.forEach(r=>{let txt=norm(r.textContent),level=levels.some(l=>r.textContent.includes(l))||$('#candProgram')?.value!=='KUMON';r.hidden=!!q&&!txt.includes(q)||!level});rows.sort((a,b)=>{let A=a.dataset[sort]||a.textContent,B=b.dataset[sort]||b.textContent;return A.localeCompare(B,'ja')}).forEach(r=>box.appendChild(r));}

// v13 recommendation browser: multi-level + title/author/publisher metadata
const metaCacheKey=P+'recommendation_meta_v1';let metaCache=load(metaCacheKey,{}),candRenderToken=0;
function candStateV13(t){return load(candKey,{})[norm(t)]||{buy:false,borrow:false}}
function setCandStateV13(t,k){let all=load(candKey,{}),n=norm(t);all[n]=all[n]||{buy:false,borrow:false};all[n][k]=!all[n][k];save(candKey,all);renderCandidatesV13()}
async function getTitleMeta(title){let n=norm(title);if(metaCache[n])return metaCache[n];let own=master().find(b=>norm(b.title)===n);if(own&&(own.author||own.publisher)){metaCache[n]={author:own.author||'',publisher:own.publisher||'',isbn:own.isbn||'',cover:cover(own)||''};save(metaCacheKey,metaCache);return metaCache[n]}
 try{let r=await fetch('https://www.googleapis.com/books/v1/volumes?q='+encodeURIComponent('intitle:'+title)+'&maxResults=3&langRestrict=ja'),j=await r.json();let items=j.items||[],it=items.find(x=>norm(x.volumeInfo?.title)===n)||items[0],v=it?.volumeInfo;if(v){let isbn=(v.industryIdentifiers||[]).find(x=>x.type==='ISBN_13')?.identifier||'';metaCache[n]={author:(v.authors||[]).join('・'),publisher:v.publisher||'',isbn,cover:(v.imageLinks?.thumbnail||'').replace('http:','https:')};save(metaCacheKey,metaCache);return metaCache[n]}}catch{} return {author:'',publisher:'',isbn:'',cover:''}}
function selectedLevels(){let a=$$('#v13Levels .on').map(x=>x.dataset.lv);return a.length?a:['5A','4A','3A','2A','A','B','C','D','E','F','G','H','I']}
function candidateTitlesV13(){let p=$('#candProgram')?.value||'KUMON',R=window.RECOMMENDATIONS||{},arr=[];if(p==='KUMON')selectedLevels().forEach(l=>(R.kumon?.[l]||[]).forEach(t=>arr.push({title:t,level:l})));else (p==='すくすく館'?R.sukusuku||[]:R.nakayoshi||[]).forEach(t=>arr.push({title:t,level:p}));let seen=new Set();return arr.filter(x=>!seen.has(norm(x.title))&&seen.add(norm(x.title)))}
async function renderCandidatesV13(){let box=$('#candidateList');if(!box||!$('#v13CandTools'))return;let token=++candRenderToken,q=norm($('#v13CandSearch')?.value),sort=$('#v13CandSort')?.value||'title',state=$('#candState')?.value||'unowned';$('#candLevel').style.display='none';let arr=candidateTitlesV13().map(x=>{let b=recBook(x.title),c=candStateV13(x.title),rc=reads().filter(r=>norm(r.title)===norm(x.title)).reduce((a,r)=>a+(+r.count||1),0),m=metaCache[norm(x.title)]||{};return {...x,b,c,rc,author:b?.author||m.author||'',publisher:b?.publisher||m.publisher||'',isbn:b?.isbn||m.isbn||'',cover:b?cover(b):m.cover||''}});if(state==='unowned')arr=arr.filter(x=>!x.b);if(state==='unread')arr=arr.filter(x=>x.b&&x.rc===0);if(state==='buy')arr=arr.filter(x=>x.c.buy);if(state==='borrow')arr=arr.filter(x=>x.c.borrow);if(q)arr=arr.filter(x=>norm(x.title+' '+x.author+' '+x.publisher).includes(q));arr.sort((a,b)=>String(a[sort]||'').localeCompare(String(b[sort]||''),'ja'));box.innerHTML=`<p><b>${arr.length}冊</b></p>`+arr.map(x=>`<div class="v8card v13-cand" data-ct="${encodeURIComponent(x.title)}">${coverEl(x)}<div style="flex:1"><b>${x.title}</b><small class="v13-cmeta">${x.author||'著者を取得中'}${x.publisher?' · '+x.publisher:''}</small><div><span class="pill">${x.level}</span><span class="pill">${x.b?'所蔵':'未所蔵'}</span><span class="pill">${x.rc?x.rc+'回':'未読'}</span></div><div class="candidate-actions"><button data-vbuy="${encodeURIComponent(x.title)}">${x.c.buy?'✓ 購入予定':'購入予定'}</button><button data-vborrow="${encodeURIComponent(x.title)}">${x.c.borrow?'✓ 図書館':'図書館'}</button><a target="_blank" rel="noopener" href="https://calil.jp/search?q=${encodeURIComponent(x.title)}">所蔵確認</a></div></div></div>`).join('');$$('[data-vbuy]').forEach(b=>b.onclick=()=>setCandStateV13(decodeURIComponent(b.dataset.vbuy),'buy'));$$('[data-vborrow]').forEach(b=>b.onclick=()=>setCandStateV13(decodeURIComponent(b.dataset.vborrow),'borrow'));
 // 外部書誌の連続取得は自動実行しない（画面を即時表示）
}
if(cdlg){$('#openCandidates')?.addEventListener('click',()=>setTimeout(renderCandidatesV13,180));['candProgram','candState'].forEach(id=>$('#'+id)?.addEventListener('change',()=>setTimeout(renderCandidatesV13,20)));$('#v13CandSearch')?.addEventListener('input',renderCandidatesV13);$('#v13CandSort')?.addEventListener('change',renderCandidatesV13);$('#v13Levels')?.addEventListener('click',()=>setTimeout(renderCandidatesV13,10))}

// Close/cancel sanity
$$('button[data-close]').forEach(b=>b.type='button');
})();

// v14: long-term home library lifecycle, full KUMON level UI, feedback and view preferences
(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const P=(window.APP_PREFIX||'kenchan_'), load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}, save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const normTitle=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[\s　・･?？!！「」『』（）()―ー\-]/g,'');
const levels=['5A','4A','3A','2A','A','B','C','D','E','F','G','H','I'];
// Candidate level controls: all 13 KUMON levels. Data is shown when included in recommendation data.
let lv=$('#v13Levels'); if(lv){lv.innerHTML=levels.map(x=>`<button type="button" class="v13-pill on" data-lv="${x}">${x}</button>`).join('')}
// About / feedback / circulation hub
let menu=$('#menu');
function dlg(id,title,html){if($('#'+id))return $('#'+id);let d=document.createElement('dialog');d.id=id;d.className='v8dlg';d.innerHTML=`<div class="shop-head"><strong>${title}</strong><button type="button" data-x>閉じる</button></div>${html}`;document.body.appendChild(d);d.querySelector('[data-x]').onclick=()=>d.close();return d}
if(menu){
 const about=document.createElement('button');about.textContent='♡ この本棚について';menu.appendChild(about);about.onclick=()=>{menu.hidden=true;dlg('v14About','この本棚について',`<div class="v14-about"><h2>本といっしょに、育っていく。</h2><p><b>たくさん持つためではなく、その子に合った「おうち図書館」を育てる。</b></p><p>見つける → 借りて試す → よく読む → 厳選して迎える → 記録する → 成長したら次の子へ。本が家を離れても、親子で読んだ記憶は残します。</p><div class="v14-flow">📚 おうち図書館　・　📖 親子の読書記録　・　♻️ 次の家庭へつなぐ</div></div>`).showModal()};
 const circ=document.createElement('button');circ.textContent='♻️ 交換・お譲りリスト';menu.appendChild(circ);circ.onclick=()=>{menu.hidden=true;renderCirculation()};
 const fb=document.createElement('button');fb.textContent='💬 ご意見・不具合';menu.appendChild(fb);fb.onclick=()=>{menu.hidden=true;openFeedback()};
}
function mergedBooks(){let ov=load(P+'clean_overrides_v1',{}),ub=load(P+'user_books_v1',[]);return [...(window.MASTER_BOOKS||[]),...ub].map(b=>({...b,...(ov[b.id]||{})})).filter(b=>!b.deleted)}
function renderCirculation(){
 let d=dlg('v14Circulation','交換・お譲りリスト','<div id="v14CircBody"></div>'),all=mergedBooks(),a=all.filter(b=>['次につなぐ本','お譲り済み','手放し候補'].includes(b.libraryStatus));
 let groups={};all.filter(b=>b.ownership==='所有'||!b.ownership).forEach(b=>{let n=normTitle(b.title);if(n)(groups[n]??=[]).push(b)});let dup=Object.values(groups).filter(g=>g.length>1);
 let registered=a.length?a.map(b=>`<div class="v8card"><b>${b.title}</b><div><span class="pill">${b.libraryStatus}</span>${b.handoffReason?`<span class="pill">理由：${b.handoffReason}</span>`:''}${b.conditionGrade?`<span class="pill">状態 ${b.conditionGrade}</span>`:''}</div></div>`).join(''):'<div class="v13-empty">まだお譲りリストへの登録はありません。</div>';
 let duplicateHtml=dup.length?dup.map(g=>`<div class="v8card"><b>重複：${g[0].title}</b><small>${g.length}冊あります。お譲りする実物を選んでください。</small>${g.map((b,i)=>`<div class="v14-dup-row"><span>${i+1}冊目${b.publisher?'｜'+b.publisher:''}${b.isbn?'｜ISBN '+b.isbn:''}</span>${b.libraryStatus==='次につなぐ本'&&b.handoffReason==='重複のため'?'<span class="pill">登録済み：重複のため</span>':`<button type="button" data-dup-handoff="${b.id}">お譲りリストに登録</button>`}</div>`).join('')}</div>`).join(''):'<div class="v13-empty">重複しているタイトルはありません。</div>';
 d.querySelector('#v14CircBody').innerHTML=`<h3>お譲りリスト</h3>${registered}<h3>重複している本</h3>${duplicateHtml}`;
 d.querySelectorAll('[data-dup-handoff]').forEach(btn=>btn.onclick=()=>{let id=btn.dataset.dupHandoff,ov=load(P+'clean_overrides_v1',{});ov[id]={...(ov[id]||{}),libraryStatus:'次につなぐ本',handoffReason:'重複のため',bookHistory:[ov[id]?.bookHistory||'',new Date().toLocaleDateString('ja-JP')+' 重複のため交換・お譲りリストに登録'].filter(Boolean).join('\n')};save(P+'clean_overrides_v1',ov);d.close();renderCirculation()});d.showModal()
}
// Extend edit dialog without touching old data.
let ed=$('#edit');if(ed&&!$('#v14Lifecycle')){let anchor=$('#enotes')?.closest('label')||$('#enotes');let sec=document.createElement('section');sec.id='v14Lifecycle';sec.className='v14-lifecycle';sec.innerHTML=`<h3>この本の記録</h3><label>本との関係<select id="v14Relation"><option value="">未設定</option><option>おうちの本</option><option>図書館の本</option><option>借りた本</option><option>その場で読んだ</option><option>読みたい</option><option>購入予定</option></select></label><label>おうち図書館での状態<select id="v14LibraryStatus"><option value="">通常</option><option>よく読む</option><option>これから活躍</option><option>季節の本</option><option>手放し候補</option><option>次につなぐ本</option><option>お譲り済み</option></select></label><label>お譲り理由<select id="v14HandoffReason"><option value="">未設定</option><option>重複のため</option><option>対象年齢を過ぎた</option><option>本棚整理</option><option>その他</option></select></label><div class="v8grid"><label>本の状態<select id="v14Condition"><option value="">未設定</option><option value="A">A ほぼ新品</option><option value="B">B きれい</option><option value="C">C 読み込みあり</option><option value="D">D 傷みあり</option></select></label><label>入手方法<select id="v14Acquire"><option value="">未設定</option><option>購入</option><option>中古購入</option><option>いただいた</option><option>図書館</option><option>譲ってもらった</option><option>その他</option></select></label></div><label>状態メモ<input id="v14ConditionFlags" placeholder="シミ・破れ・折れ・書き込み・記名など"></label><label>入手・お譲りの記録<textarea id="v14History" placeholder="例：2026/09/27 BOOKOFFで購入"></textarea></label>`;(anchor||ed).after(sec)}
function fillLife(){let id=$('#eid')?.value,b=mergedBooks().find(x=>x.id===id);if(!b)return;$('#v14Relation').value=b.relation||'';$('#v14LibraryStatus').value=b.libraryStatus||'';$('#v14HandoffReason').value=b.handoffReason||'';$('#v14Condition').value=b.conditionGrade||'';$('#v14Acquire').value=b.acquireType||'';$('#v14ConditionFlags').value=b.conditionFlags||'';$('#v14History').value=b.bookHistory||''}
// capture after legacy edit opener fills id
if(ed)new MutationObserver(()=>{if(ed.open)setTimeout(fillLife,0)}).observe(ed,{attributes:true,attributeFilter:['open']});
$('#save')?.addEventListener('click',()=>{let id=$('#eid')?.value;if(!id)return;let ov=load(P+'clean_overrides_v1',{});ov[id]={...(ov[id]||{}),relation:$('#v14Relation')?.value||'',libraryStatus:$('#v14LibraryStatus')?.value||'',handoffReason:$('#v14HandoffReason')?.value||'',conditionGrade:$('#v14Condition')?.value||'',acquireType:$('#v14Acquire')?.value||'',conditionFlags:$('#v14ConditionFlags')?.value||'',bookHistory:$('#v14History')?.value||''};save(P+'clean_overrides_v1',ov)},true);
// Feedback package. Screenshot is user-selected only; no child/library data is auto-attached.
function openFeedback(){let screens=['本棚','お店で本をさがす','本を登録','読み聞かせ','さがす・候補','今月のおすすめ','分析','月間記録・目標','設定','この本棚について','交換・お譲りリスト','ご意見・不具合','その他'];let d=dlg('v14Feedback','ご意見・不具合',`<p class="v8meta">子どもの名前・蔵書・読書メモは送信内容に自動追加しません。</p><label>種類<select id="v14FbType"><option>🐞 不具合</option><option>💡 欲しい機能</option></select></label><label>どの画面ですか<select id="v14FbScreen">${screens.map(x=>`<option>${x}</option>`).join('')}</select></label><label id="v14OtherWrap" class="v14-other" hidden>その他の画面名<input id="v14FbOther" placeholder="画面名を入力"></label><label>内容<textarea id="v14FbText" placeholder="何をしたら、どうなったか"></textarea></label><label>スクリーンショット（任意）<input id="v14FbImage" type="file" accept="image/*"></label><div class="v14-feedback-actions"><button class="shop-primary" id="v14SendReport">送信</button></div><div id="v14FbOut"></div>`);d.showModal();let screen=$('#v14FbScreen');screen.onchange=()=>{$('#v14OtherWrap').hidden=screen.value!=='その他'};$('#v14SendReport').onclick=async()=>{let text=$('#v14FbText').value.trim();if(!text)return alert('内容を入力してください');let item={id:'FB-'+Date.now(),type:$('#v14FbType').value,screen:screen.value==='その他'?($('#v14FbOther').value.trim()||'その他'):screen.value,text,hasImage:!!$('#v14FbImage').files[0],app:'v14.4',createdAt:new Date().toISOString(),userAgent:navigator.userAgent};let list=load(P+'feedback_v1',[]);list.push(item);save(P+'feedback_v1',list);$('#v14FbOut').innerHTML='<div class="v14-sent">送信しました。ありがとうございます。</div>';setTimeout(()=>d.close(),900)}}
// View preference: automatic / mobile / PC.
let sd=$('#settingsDlg');if(sd&&!$('#v14ViewMode')){let sec=document.createElement('section');sec.innerHTML=`<h3>表示</h3><label>表示モード<select id="v14ViewMode"><option value="auto">自動</option><option value="mobile">📱 スマホ表示</option><option value="pc">🖥 PC表示</option></select></label>`;sd.querySelector('.shop-head').after(sec);let k=P+'view_mode_v1',v=localStorage.getItem(k)||'auto';$('#v14ViewMode').value=v;const apply=x=>{document.documentElement.dataset.view=x;localStorage.setItem(k,x)};apply(v);$('#v14ViewMode').onchange=e=>apply(e.target.value)}
})();

