(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const readKey='kenchan_reading_events_v2', monthKey='kenchan_monthly_records_v2', settingsKey='kenchan_settings_v2', candKey='kenchan_candidates_v2', coverKey='kenchan_covers_v1';
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}}, save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let reads=load(readKey,null); if(!Array.isArray(reads)){reads=(window.MIETE_SEED||[]).filter(x=>x.kind==='book');save(readKey,reads)}
let months=load(monthKey,{}), settings=load(settingsKey,{name:'けんいち',honor:'くん',birthday:'2025-04-05',goal:10000,monthGoal:500,calilKey:'',libs:[{label:'A',name:'メイン図書館',systemid:'',url:''},{label:'B',name:'第2図書館',systemid:'',url:''},{label:'C',name:'第3図書館',systemid:'',url:''}]}), candidates=load(candKey,{}), covers=load(coverKey,{});
const master=()=>{const ov=load('kenchan_clean_overrides_v1',{}), ub=load('kenchan_user_books_v1',[]);return [...(window.MASTER_BOOKS||[]),...ub].map(b=>({...b,...(ov[b.id]||{})})).filter(b=>!b.deleted)};
const norm=s=>(s||'').normalize('NFKC').toLowerCase().replace(/[\s　・･?？!！「」『』（）()―ー\-]/g,'').replace(/がたんごとんがたんごとん/g,'がたんごとんがたんごとん').replace(/ぐるんぱのようちえん/g,'ぐるんぱようちえん').replace(/^新版/,'');
function owned(title){let n=norm(title);return master().find(b=>norm(b.title)===n || (n.length>5&&(norm(b.title).includes(n)||n.includes(norm(b.title))))) }
function readCount(title){let n=norm(title);return reads.filter(r=>{let x=norm(r.title);return x===n||(n.length>5&&(x.includes(n)||n.includes(x)))}).reduce((a,r)=>a+(+r.count||1),0)}
function allReadCount(){return reads.reduce((a,r)=>a+(+r.count||1),0)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ageAt(date){if(!settings.birthday)return'';let b=new Date(settings.birthday+'T00:00:00'),d=new Date(date+'-01T00:00:00');let m=(d.getFullYear()-b.getFullYear())*12+d.getMonth()-b.getMonth();return m<0?'':`${Math.floor(m/12)}歳${m%12}か月`}
function updateBrand(){document.querySelector('header b').textContent=`${settings.name||''}${settings.honor||''}の本棚`}
updateBrand();
$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
function menuOpen(id,render){const b=$('#'+id); if(!b)return;b.onclick=()=>{$('#menu').hidden=true;render&&render();$('#'+id.replace('open','').replace(/^./,c=>c.toLowerCase())+'Dlg')?.showModal()}}
// Bibliographic lookup
async function lookupBib(isbn){isbn=(isbn||$('#eisbn').value).replace(/\D/g,'');if(!/^97[89]\d{10}$/.test(isbn)){if($('#bibMsg'))$('#bibMsg').textContent='13桁のISBNを入力してください。';return}$('#bibMsg').textContent='書誌情報を検索中…';try{let r=await fetch('https://api.openbd.jp/v1/get?isbn='+isbn);let j=await r.json(),d=j&&j[0];if(!d)throw new Error('not found');let sm=d.summary||{}; if(sm.title)$('#etitle').value=sm.title;if(sm.author)$('#eauthor').value=sm.author;if(sm.publisher)$('#epublisher').value=sm.publisher;if(sm.cover){covers[isbn]=sm.cover;save(coverKey,covers)}$('#bibMsg').textContent='openBDからタイトル・著者・出版社を取得しました。内容を確認して「登録」を押してください。'}catch(e){$('#bibMsg').innerHTML='openBDでは見つかりませんでした。<a target="_blank" href="https://ndlsearch.ndl.go.jp/search?cs=bib&keyword='+encodeURIComponent(isbn)+'">国立国会図書館サーチで確認</a>'}}
window.lookupBib=lookupBib; $('#lookupBib').onclick=()=>lookupBib();
// reading
function renderReading(){let total=allReadCount();$('#readingSummary').innerHTML=`<div class="v8card"><b>取り込み済み読み聞かせ ${total.toLocaleString()}回</b><div class="v8meta">ミーテPDF＋アプリ内記録</div></div>`;$('#bookTitles').innerHTML=master().map(b=>`<option value="${esc(b.title)}">`).join('');$('#readDate').value=new Date().toISOString().slice(0,10);$('#recentReads').innerHTML=reads.slice(-20).reverse().map(r=>`<div class="v8card"><b>${esc(r.title)}</b> ${r.count}回<div class="v8meta">${r.date} ${r.time||''}${r.reaction?'｜'+esc(r.reaction):''}</div></div>`).join('')}
$('#openReading').onclick=()=>{$('#menu').hidden=true;renderReading();$('#readingDlg').showModal()};$('#saveRead').onclick=()=>{let t=$('#readTitle').value.trim();if(!t)return alert('タイトルを入力してください');reads.push({date:$('#readDate').value,time:new Date().toTimeString().slice(0,5),title:t,count:+$('#readCount').value||1,reaction:$('#readReaction').value.trim(),source:'app'});save(readKey,reads);$('#readTitle').value='';$('#readReaction').value='';renderReading();};
// candidates
function recList(){let p=$('#candProgram').value,l=$('#candLevel').value;if(p==='KUMON')return (window.RECOMMENDATIONS?.kumon?.[l]||[]);return p==='すくすく館'?(window.RECOMMENDATIONS?.sukusuku||[]):window.RECOMMENDATIONS?.nakayoshi||[]}
function candidateState(title){return candidates[norm(title)]||{buy:false,borrow:false}}
function renderCandidates(){let p=$('#candProgram').value,state=$('#candState').value;$('#candLevel').style.display=p==='KUMON'?'':'none';let a=recList().map(t=>({title:t,b:owned(t),rc:readCount(t),c:candidateState(t)}));if(state==='unowned')a=a.filter(x=>!x.b);if(state==='unread')a=a.filter(x=>x.b&&x.rc===0);if(state==='buy')a=a.filter(x=>x.c.buy);if(state==='borrow')a=a.filter(x=>x.c.borrow);$('#candidateList').innerHTML=`<p><b>${a.length}冊</b></p>`+a.map(x=>{let isbn=x.b?.isbn||'';return `<div class="v8card"><b>${esc(x.title)}</b><div><span class="pill">${x.b?'所蔵':'未所蔵'}</span><span class="pill">${x.rc?x.rc+'回読了':'未読'}</span></div><div class="candidate-actions"><button data-buy="${esc(x.title)}">${x.c.buy?'✓ 購入候補':'購入候補へ'}</button><button data-borrow="${esc(x.title)}">${x.c.borrow?'✓ 借りる候補':'借りる候補へ'}</button><a target="_blank" href="https://api.calil.jp/openurl?rft.${isbn?'isbn':'btitle'}=${encodeURIComponent(isbn||x.title)}">図書館検索</a>${x.c.borrow?`<button data-libcheck="${esc(x.title)}">A/B/C所蔵確認</button>`:''}</div><div id="lib-${Math.abs(hash(x.title))}"></div></div>`}).join('');$$('[data-buy]').forEach(b=>b.onclick=()=>toggleCand(b.dataset.buy,'buy'));$$('[data-borrow]').forEach(b=>b.onclick=()=>toggleCand(b.dataset.borrow,'borrow'));$$('[data-libcheck]').forEach(b=>b.onclick=()=>checkLibraries(b.dataset.libcheck))}
function hash(s){let h=0;for(let c of s)h=((h<<5)-h)+c.charCodeAt(0)|0;return h}
function toggleCand(t,k){let n=norm(t),c=candidates[n]||{title:t,buy:false,borrow:false};c[k]=!c[k];candidates[n]=c;save(candKey,candidates);renderCandidates()}
['candProgram','candLevel','candState'].forEach(id=>$('#'+id).onchange=renderCandidates);$('#openCandidates').onclick=()=>{$('#menu').hidden=true;renderCandidates();$('#candidateDlg').showModal()};
function jsonp(url){return new Promise((res,rej)=>{let cb='calil_'+Date.now()+'_'+Math.floor(Math.random()*9999),s=document.createElement('script'),tm=setTimeout(()=>{cleanup();rej(new Error('timeout'))},15000);function cleanup(){clearTimeout(tm);delete window[cb];s.remove()}window[cb]=d=>{cleanup();res(d)};s.onerror=()=>{cleanup();rej(new Error('error'))};s.src=url+(url.includes('?')?'&':'?')+'callback='+cb;document.body.appendChild(s)})}
async function checkLibraries(title){let el=$('#lib-'+Math.abs(hash(title))),b=owned(title),isbn=(b?.isbn||'').replace(/\D/g,'');if(!settings.calilKey)return el.innerHTML='<div class="v8meta">設定でカーリルAPIキーを登録するとA/B/Cの所蔵状況を表示できます。</div>';if(!isbn)return el.innerHTML='<div class="v8meta">ISBN未登録のためリアルタイム所蔵確認はできません。上の「図書館検索」を利用してください。</div>';let libs=(settings.libs||[]).filter(x=>x.systemid);if(!libs.length)return el.innerHTML='<div class="v8meta">設定で図書館A/B/CのシステムIDを登録してください。</div>';el.textContent='所蔵確認中…';try{let sys=libs.map(x=>x.systemid).join(','),url=`https://api.calil.jp/check?appkey=${encodeURIComponent(settings.calilKey)}&isbn=${isbn}&systemid=${encodeURIComponent(sys)}&format=json`;let d=await jsonp(url);for(let i=0;i<8&&d.continue;i++){await new Promise(r=>setTimeout(r,2100));d=await jsonp(`https://api.calil.jp/check?appkey=${encodeURIComponent(settings.calilKey)}&session=${encodeURIComponent(d.session)}&format=json`)}let book=d.books?.[isbn]||d.books?.[Object.keys(d.books||{})[0]]||{};el.innerHTML=libs.map(L=>{let z=book[L.systemid],vals=z?Object.values(z.libkey||{}):[],yes=vals.length>0,avail=vals.includes('貸出可'),mark=avail?'◎':yes?'○':'×',link=z?.reserveurl||L.url||'';return `<span class="libstat">${L.label} ${esc(L.name)} ${mark}${avail?' 貸出可':''}</span>${link?`<a target="_blank" href="${esc(link)}">予約/検索</a>`:''}`}).join(' ')}catch(e){el.textContent='所蔵確認に失敗しました。図書館検索リンクをご利用ください。'}}
// analytics
function renderAnalytics(){let by={};reads.forEach(r=>by[r.title]=(by[r.title]||0)+(+r.count||1));let top=Object.entries(by).sort((a,b)=>b[1]-a[1]).slice(0,15);let monthsMap={};reads.forEach(r=>{let m=r.date?.slice(0,7)||'不明';monthsMap[m]=(monthsMap[m]||0)+(+r.count||1)});$('#analyticsBody').innerHTML=`<div class="v8grid"><div class="v8card"><b>累計 ${allReadCount().toLocaleString()}回</b><div class="v8meta">目標 ${(settings.goal||0).toLocaleString()}回</div><div class="goalbar"><i style="width:${settings.goal?Math.min(100,allReadCount()/settings.goal*100):0}%"></i></div></div><div class="v8card"><b>${Object.keys(by).length}タイトル</b></div></div><h3>月別</h3>${Object.entries(monthsMap).sort().map(x=>`<div class="v8card">${x[0]} <b>${x[1]}回</b></div>`).join('')}<h3>よく読んだ本</h3>${top.map((x,i)=>`<div class="v8card">${i+1}. <b>${esc(x[0])}</b> ${x[1]}回</div>`).join('')}`}
$('#openAnalytics').onclick=()=>{$('#menu').hidden=true;renderAnalytics();$('#analyticsDlg').showModal()};
// monthly
function monthReads(m){return reads.filter(r=>r.date?.startsWith(m))}function renderMonth(){let m=$('#monthKey').value||new Date().toISOString().slice(0,7),rr=monthReads(m),cnt=rr.reduce((a,r)=>a+(+r.count||1),0),goal=+settings.monthGoal||0,rec=months[m]||{};$('#monthEvents').value=rec.events||'';$('#monthComment').value=rec.comment||'';$('#monthBookMemo').value=rec.bookMemo||'';let by={};rr.forEach(r=>by[r.title]=(by[r.title]||0)+(+r.count||1));let top=Object.entries(by).sort((a,b)=>b[1]-a[1]).slice(0,5);$('#monthStats').innerHTML=`<div class="v8card"><b>${m} ${ageAt(m)}</b><p>${cnt}回／${Object.keys(by).length}タイトル　月間目標 ${goal||'-'}回</p><div class="goalbar"><i style="width:${goal?Math.min(100,cnt/goal*100):0}%"></i></div><h4>よく読んだ本</h4>${top.map(x=>`${esc(x[0])} ${x[1]}回`).join('<br>')}</div>`;$('#photoPreview').innerHTML=(rec.photos||[]).map(x=>`<img class="month-photo" src="${x}">`).join('')}
$('#openMonthly').onclick=()=>{$('#menu').hidden=true;$('#monthKey').value=new Date().toISOString().slice(0,7);renderMonth();$('#monthlyDlg').showModal()};$('#monthKey').onchange=renderMonth;
async function compress(file){return new Promise((res,rej)=>{let fr=new FileReader;fr.onload=()=>{let im=new Image;im.onload=()=>{let scale=Math.min(1,900/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=im.width*scale;c.height=im.height*scale;c.getContext('2d').drawImage(im,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.72))};im.src=fr.result};fr.onerror=rej;fr.readAsDataURL(file)})}
$('#saveMonth').onclick=async()=>{let m=$('#monthKey').value,old=months[m]||{},photos=old.photos||[];for(let f of [...$('#monthPhotos').files].slice(0,3-photos.length))photos.push(await compress(f));months[m]={events:$('#monthEvents').value,comment:$('#monthComment').value,bookMemo:$('#monthBookMemo').value,photos};try{save(monthKey,months)}catch(e){alert('写真データが大きすぎます。写真を減らしてください。');return}renderMonth();alert('月間記録を保存しました。')};
async function exportPDF(){let keys=[...new Set([...Object.keys(months),...reads.map(r=>r.date?.slice(0,7)).filter(Boolean)])].sort(),selected=$('#monthKey').value;if(!keys.includes(selected))keys.push(selected);keys=[...new Set(keys)].sort();let per=$('#pdfPeriod').value;if(per!=='all')keys=keys.slice(-(+per));let pages=keys.map(m=>{let rec=months[m]||{},rr=monthReads(m),by={};rr.forEach(r=>by[r.title]=(by[r.title]||0)+(+r.count||1));let top=Object.entries(by).sort((a,b)=>b[1]-a[1]);let coverHtml=top.slice(0,5).map(x=>{let b=owned(x[0]),u=b?.isbn?covers[b.isbn]:'';return u?`<div style="display:inline-block;width:18%;vertical-align:top;text-align:center"><img crossorigin="anonymous" src="${esc(u)}" style="max-width:90%;max-height:120px"><br><small>${esc(x[0])} ${x[1]}回</small></div>`:''}).join('');return `<section class="page"><h1>${esc(settings.name)}${esc(settings.honor)}の読書と成長の記録</h1><h2>${m}　${ageAt(m)}</h2><p>読み聞かせ ${rr.reduce((a,r)=>a+(+r.count||1),0)}回／${Object.keys(by).length}タイトル</p>${coverHtml?`<h3>今月よく読んだ本</h3><div>${coverHtml}</div>`:''}<h3>今月読んだ本</h3><p>${top.slice(0,20).map(x=>`${esc(x[0])}（${x[1]}回）`).join('、')}</p>${rec.bookMemo?`<h3>本の思い出</h3><p>${esc(rec.bookMemo)}</p>`:''}${rec.events?`<h3>できごと・成長</h3><p>${esc(rec.events)}</p>`:''}${rec.comment?`<h3>家族から</h3><p>${esc(rec.comment)}</p>`:''}<div>${(rec.photos||[]).map(x=>`<img src="${x}">`).join('')}</div></section>`}).join('');let pb=$('#printBook');pb.innerHTML=pages;if(!window.html2pdf){await new Promise((res,rej)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/html2pdf.js@0.10.2/dist/html2pdf.bundle.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}html2pdf().set({margin:8,filename:`${settings.name}${settings.honor}_読書成長記録.pdf`,html2canvas:{scale:2},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css','legacy']}}).from(pb).save()}
$('#exportPdf').onclick=()=>exportPDF().catch(()=>{alert('PDF生成ライブラリを読み込めませんでした。印刷画面を開きます。');window.print()});
// settings
function renderSettings(){ $('#setName').value=settings.name||'';$('#setHonor').value=settings.honor||'';$('#setBirthday').value=settings.birthday||'';$('#setGoal').value=settings.goal||10000;$('#setMonthGoal').value=settings.monthGoal||500;$('#setCalilKey').value=settings.calilKey||'';$('#libSettings').innerHTML=(settings.libs||[]).map((L,i)=>`<div class="v8card"><b>${L.label}${i===0?'（メイン）':''}</b><input data-ln="${i}" value="${esc(L.name||'')}" placeholder="図書館名"><input data-ls="${i}" value="${esc(L.systemid||'')}" placeholder="カーリル systemid"><input data-lu="${i}" value="${esc(L.url||'')}" placeholder="図書館予約・検索URL"></div>`).join('')}
$('#openSettings').onclick=()=>{$('#menu').hidden=true;renderSettings();$('#settingsDlg').showModal()};$('#saveSettings').onclick=()=>{settings.name=$('#setName').value.trim();settings.honor=$('#setHonor').value;settings.birthday=$('#setBirthday').value;settings.goal=+$('#setGoal').value||10000;settings.monthGoal=+$('#setMonthGoal').value||0;settings.calilKey=$('#setCalilKey').value.trim();settings.libs=(settings.libs||[]).map((L,i)=>({...L,name:$(`[data-ln="${i}"]`).value.trim(),systemid:$(`[data-ls="${i}"]`).value.trim(),url:$(`[data-lu="${i}"]`).value.trim()}));save(settingsKey,settings);updateBrand();$('#settingsDlg').close();alert('設定を保存しました。')};
})();
